/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as OpEdRouteImport } from './routes/op-ed'
import { Route as PoliticsRouteImport } from './routes/politics'
import { Route as StoryIdRouteImport } from './routes/story.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const OpEdRoute = OpEdRouteImport.update({
  id: '/op-ed',
  path: '/op-ed',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticsRoute = PoliticsRouteImport.update({
  id: '/politics',
  path: '/politics',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIdRoute = StoryIdRouteImport.update({
  id: '/story/$id',
  path: '/story/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/culture': typeof CultureRoute
  '/op-ed': typeof OpEdRoute
  '/politics': typeof PoliticsRoute
  '/story/$id': typeof StoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/culture': typeof CultureRoute
  '/op-ed': typeof OpEdRoute
  '/politics': typeof PoliticsRoute
  '/story/$id': typeof StoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/culture': typeof CultureRoute
  '/op-ed': typeof OpEdRoute
  '/politics': typeof PoliticsRoute
  '/story/$id': typeof StoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/culture'
    | '/op-ed'
    | '/politics'
    | '/story/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/culture'
    | '/op-ed'
    | '/politics'
    | '/story/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/culture'
    | '/op-ed'
    | '/politics'
    | '/story/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CultureRoute: typeof CultureRoute
  OpEdRoute: typeof OpEdRoute
  PoliticsRoute: typeof PoliticsRoute
  StoryIdRoute: typeof StoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/op-ed': {
      id: '/op-ed'
      path: '/op-ed'
      fullPath: '/op-ed'
      preLoaderRoute: typeof OpEdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politics': {
      id: '/politics'
      path: '/politics'
      fullPath: '/politics'
      preLoaderRoute: typeof PoliticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$id': {
      id: '/story/$id'
      path: '/story/$id'
      fullPath: '/story/$id'
      preLoaderRoute: typeof StoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CultureRoute: CultureRoute,
  OpEdRoute: OpEdRoute,
  PoliticsRoute: PoliticsRoute,
  StoryIdRoute: StoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
