/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApiPipelinePickRouteImport } from './routes/api.pipeline-pick'
import { Route as ApiSetupSeedRouteImport } from './routes/api.setup-seed'
import { Route as StoryIdRouteImport } from './routes/story.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPipelinePickRoute = ApiPipelinePickRouteImport.update({
  id: '/api/pipeline-pick',
  path: '/api/pipeline-pick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupSeedRoute = ApiSetupSeedRouteImport.update({
  id: '/api/setup-seed',
  path: '/api/setup-seed',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIdRoute = StoryIdRouteImport.update({
  id: '/story/$id',
  path: '/story/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/api/pipeline-pick': typeof ApiPipelinePickRoute
  '/api/setup-seed': typeof ApiSetupSeedRoute
  '/story/$id': typeof StoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/api/pipeline-pick': typeof ApiPipelinePickRoute
  '/api/setup-seed': typeof ApiSetupSeedRoute
  '/story/$id': typeof StoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/api/pipeline-pick': typeof ApiPipelinePickRoute
  '/api/setup-seed': typeof ApiSetupSeedRoute
  '/story/$id': typeof StoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/api/pipeline-pick'
    | '/api/setup-seed'
    | '/story/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/api/pipeline-pick'
    | '/api/setup-seed'
    | '/story/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/api/pipeline-pick'
    | '/api/setup-seed'
    | '/story/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ApiPipelinePickRoute: typeof ApiPipelinePickRoute
  ApiSetupSeedRoute: typeof ApiSetupSeedRoute
  StoryIdRoute: typeof StoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pipeline-pick': {
      id: '/api/pipeline-pick'
      path: '/api/pipeline-pick'
      fullPath: '/api/pipeline-pick'
      preLoaderRoute: typeof ApiPipelinePickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup-seed': {
      id: '/api/setup-seed'
      path: '/api/setup-seed'
      fullPath: '/api/setup-seed'
      preLoaderRoute: typeof ApiSetupSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$id': {
      id: '/story/$id'
      path: '/story/$id'
      fullPath: '/story/$id'
      preLoaderRoute: typeof StoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ApiPipelinePickRoute: ApiPipelinePickRoute,
  ApiSetupSeedRoute: ApiSetupSeedRoute,
  StoryIdRoute: StoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
